openapi: 3.0.1
info:
  title: TamweelyAPI
  description: API Definition of TamweelyAPI
  version: 1.0.0
servers:
  - url: http://localhost:8290/api/tamweely
  - url: https://localhost:8253/api/tamweely
paths:
  /:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
